### ISSUE TITLE
Missing dependecy in www/package.json

### ISSUE THREAD

**Issue by inspirsea** [rustwasm/wasm_game_of_life#41]
package.json doesen't contain a dependency to wasm-game-of-life.

Making the web app fail at runtime with:
ERROR in ./index.js                                       
Module not found: Error: Can't resolve 'wasm-game-of-life'

**Comment by fitzgen** [comment]
Thanks for filing an issue.

You have to follow the `npm link` related instructions from the book: https://rustwasm.github.io/book/game-of-life/hello-world.html#using-our-local-wasm-game-of-life-package-in-www

Feel free to re-open if that doesn't fix the problem!

**Comment by mki1967** [comment]
I needed to add `/` after the `file:../pkg`:
```
  "dependencies": {
    "wasm-game-of-life": "file:../pkg/"
  },
```

**Comment by xadil** [comment]
I had a similar issue and adding / as in `file:../pkg/` worked for me. Thanks a lot @mki1967

**Comment by seanaye** [comment]
Adding the trailing slash does not work for me with yarn nor npm. Is there another solution anyone has found?

**Comment by NarpyNarwhal** [comment]
Had the same issue. For me, the issue was caused by the package.json file not being generated by the `wasm-pack build` command.

You can create the package.json file yourself and copy/paste the contents from the tutorial.

**Comment by PrisionMike** [comment]
Putting the / after pkg doesn't work for me either.
I am using Debian  10 WSL

**Comment by imaitland** [comment]
This error is likely caused by starting the project with some name other than `wasm_game_of_life`, at this stage: `cargo generate --git https://github.com/rustwasm/wasm-pack-template` you are prompted for a project name, it's likely you diverged from the norm, in my case:

```
import { memory } from "wasm-game-of-life/wasm_game_of_life_bg";
```
It should be:
```
import { memory } from "wasm-game-of-life/game_of_life_bg";
```

**Comment by pinkponk** [comment]
Also use another name for the crate. For me when I had this problem I had a simple copy/paste error. Was using - instead of _

Changed from this:
`import { memory } from "wasm-conway-of-life/wasm-conway-of-life_bg";`
To this:
`import { memory } from "wasm-conway-of-life/wasm_conway_of_life_bg";`

**Comment by Moto42** [comment]
Had problem.  
Came here.  
Fixed 2 problems from suggestions in this thread.  
Still nothing.  
*Eventually* find typo.
Friendly reminder to doublecheck your spelling of `wasm_game_of_life` in the import.

**Comment by AlfredoPrades** [comment]
In my case the problem was that the comand `wasm-pack build` wasn't creating the package.json file in the pkg folder.
I created it manually, with the content provided in the example and it worked.

`{
  "name": "wasm-game-of-life",
  "collaborators": [
    "Your Name <your.email@example.com>"
  ],
  "description": null,
  "version": "0.1.0",
  "license": null,
  "repository": null,
  "files": [
    "wasm_game_of_life_bg.wasm",
    "wasm_game_of_life.d.ts"
  ],
  "main": "wasm_game_of_life.js",
  "types": "wasm_game_of_life.d.ts"
}`
