### ISSUE TITLE
Not able to get passed piping string into javascript

### ISSUE THREAD

**Issue by PrismaPhonic** [rustwasm/wasm_game_of_life#43]
Hi, I've gotten towards the end of section 4 in chapter 4 of the tutorial - the end of 'Rendering with Javascript'.  The problem is that I only get the initial render, but it doesn't seem that I get any animation at all.  I get an error in the console that links to some of the web assembly (and I can't personally understand the raw web assembly).  The console error (Javascript) I keep getting is: RuntimeError: unreachable executed.  Any help?

**Comment by PrismaPhonic** [comment]
Actually, might be webpack related as I sometimes see this error right before it onn some refreshes: https://github.com/webpack/webpack-dev-server/issues/851

**Comment by PrismaPhonic** [comment]
Actually, I downgraded my webpack to see if that was it and no dice.  Have no idea why I can't seem to get this working at all.  It only renders the first frame and then I get a "RuntimeError: unreachable executed" error and no sense of how to fix this.  I followed the guide exactly and triple checked all of my code

**Comment by PrismaPhonic** [comment]
closing this issue - turned out to be a typo I made in the tick function - very facepalm moment over here.  Sorry to open this ticket!

**Comment by fitzgen** [comment]
@PrismaPhonic can you share the exact messages in full from the console? Can you also put your exact version of the tutorial code up on github somewhere so we can try and reproduce the issue? One more thing to check: if you clone this repo, does it work for you?

**Comment by fitzgen** [comment]
> closing this issue - turned out to be a typo I made in the tick function - very facepalm moment over here. Sorry to open this ticket!

er oops missed this message. Glad to hear you figured it out! :)
