### ISSUE TITLE
Move more parts of the tutorial to rust

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm_game_of_life#49]
There are parts in tutorial like this:
```javascript
// Import the WebAssembly memory at the top of the file.
import { memory } from "wasm-game-of-life/wasm_game_of_life_bg";

// ...

const getIndex = (row, column) => {
  return row * width + column;
};

const drawCells = () => {
  const cellsPtr = universe.cells();
  const cells = new Uint8Array(memory.buffer, cellsPtr, width * height);

  ctx.beginPath();

  for (let row = 0; row < height; row++) {
    for (let col = 0; col < width; col++) {
      const idx = getIndex(row, col);

      ctx.fillStyle = cells[idx] === Cell.Dead
        ? DEAD_COLOR
        : ALIVE_COLOR;

      ctx.fillRect(
        col * (CELL_SIZE + 1) + 1,
        row * (CELL_SIZE + 1) + 1,
        CELL_SIZE,
        CELL_SIZE
      );
    }
  }

  ctx.stroke();
};
```
We can move them to rust

**Comment by ibaryshnikov** [comment]
Here is an example how it may look like
https://github.com/ibaryshnikov/wasm_game_of_life/blob/master/src/lib.rs#L170
If you like an idea, I'll submit a pr

**Comment by fitzgen** [comment]
I think it is valuable to show off how to have JS and Rust/Wasm interact with each other. While the whole game of life could definitely be implemented in Rust/Wasm without any hand-written JS, it wouldn't help people learn the skills necessary for incrementally replacing some JS module with Rust and having them work well with each other.

**Comment by ibaryshnikov** [comment]
@fitzgen sounds reasonable

**Comment by tyt2y3** [comment]
Hi all! I am new to the rust community. I tried to implement all javascript in pure rust. Here is my branch. I can't create a pull request though (because cannot request a new branch).

https://github.com/tyt2y3/wasm_game_of_life/commit/19903c9b6c26b40731cde31a29882f28734fe0b4
https://github.com/tyt2y3/wasm_game_of_life/tree/pure-rust
